### PR TITLE
Update to freedesktop 23.08

### PR DESCRIPTION
**Pull request by dreua**

### CODE REVIEW

**Comment by dreua** [comment]
Let's see if it builds, see also #51

**Comment by dreua** [comment]
Maybe 24.08 would be even better :thinking:

**Comment by leamas** [comment]
It's not that simple, sorry. Updating OpenCPN must be coordinated with new builds of all plugins.  This is a major undertaking which must be handled upstream

**Comment by dreua** [comment]
Alright, thanks! Won't happen again :wink:

**Pull request closed without merging**
