### PR TITLE
5.8.2-1: Fix canbus permissions (opencpn/opencpn#3307)

### PR DESCRIPTION
**Pull request by leamas**
Update manifest to handle  https://github.com/OpenCPN/OpenCPN/issues/3307

### CODE REVIEW

**Comment by bdbcat** [comment]
If possible, we should have the OP verify this test build.

**Comment by leamas** [comment]
Yes, this discussion in https://github.com/OpenCPN/OpenCPN/issues/3307

**Comment by bdbcat** [comment]
Great, I'll monitor.

**Comment by bdbcat** [comment]
Thanks

**Pull request merged**
